### ISSUE TITLE
SvgStorePlugin fails if there are any other unrelated errors in the build

### ISSUE THREAD

**Issue by mihkeleidast** [bensampaio/external-svg-sprite-loader#92]
Hey! I've run into an issue when there's some sort of error in my build (for example, an eslint error that comes via eslint-loader), then SvgStorePlugin fails. That's probably because webpack does not emit if there are any errors.

Versions (ask if anything else may be of importance):
```
"webpack": "^5.16.0"
"external-svg-sprite-loader": "^7.1.1"
```

Stack trace:
```
/home/mihkel/dev/garage/wordpress-base/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:223
                    if (typeof source._name === 'string') {
                                      ^

TypeError: Cannot read property '_name' of null
    at SvgStorePlugin.replaceSpritePathsInModuleWithInterpolatedPaths (/home/mihkel/dev/garage/wordpress-base/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:223:39)
    at SvgStorePlugin.fixSpritePathsInModules (/home/mihkel/dev/garage/wordpress-base/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:97:22)
    at Hook.eval [as call] (eval at create (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at Hook.CALL_DELEGATE [as _call] (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/Compilation.js:2096:37)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/Compiler.js:1054:20
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/Compilation.js:1925:4
    at _next4 (eval at create (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at eval (eval at create (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:1)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:332:11
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2850:39)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:311:18
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/mihkel/dev/garage/wordpress-base/node_modules/webpack/node_modules/neo-async/async.js:2850:39)
    at /home/mihkel/dev/garage/wordpress-base/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:46:16
```

**Comment by mihkeleidast** [comment]
Should be fixed in #96!
